#!/usr/bin/env python3
import argparse
import json
import subprocess
import webbrowser
import modules.PySimpleGUI as sg

from modules.persistence import QuizQuestion
from modules.checker import is_silly

changes = False
questionList = []
current_file_path = None
difficultyList = [i for i in range(1, 6)]

menuBar = [
    ['&File', ['&Clear', '&New', '&Open', '&Save', 'Save &As', '---', '&Restart', '&Quit']],
    ['&Edit', ['&Add Question', '&Edit Question', 'Dupli&cate Question', '&Delete Question']],
    ['!&View', ['&Question Overview', '!&Editor', '&Raw JSON']],
    ['&Run', ['&Play']],
    ['&Help', ['!About', '&Tutorials', '&Github', ['QuizMaster &Repository', 'QuizMaster &Organisation']]]
]
mainWindowLayout = [
    [sg.Menu(menuBar)],
    [sg.Text("Title of Quiz:"), sg.InputText(key='quiz_name', tooltip="The title of the quiz that players will see.")],
    [sg.Text("Difficulty:", tooltip="Select the difficulty level for this quiz (1 = Baby Quiz, 3 = Secondary School Level, 5 = Requires a professional understanding of the subject)."),
     sg.Spin(difficultyList, key='difficulty', initial_value=3)],
    [sg.Checkbox("Randomize Questions", default=False, tooltip="Randomize the order of questions when the quiz is played.", key='randomOrder')],
    [sg.Listbox(questionList, size=(150, 20), font=("Calibri", 12), expand_x = True, expand_y = True, key='quizquestionentry', enable_events=True, tooltip="The list of the questions."),
     sg.Text(key='textbox', size=(20, 10))],
    [sg.Button("Add Question", tooltip="Add a new question."), sg.Button("Edit Question", tooltip="Select a question from the listbox to edit."),
     sg.Button('Duplicate Question', tooltip="Duplicate the selected question"),
     sg.Button("Delete Question", tooltip="Select a question from the listbox to delete.")],
    [sg.Button('Quit')]
]

mainWindow = sg.Window('Quiz Creator', mainWindowLayout, return_keyboard_events=True, resizable = True, finalize=True, use_default_focus=False)

def make_questionEditorWindow():
    questionEditorLayout = [
        [sg.Text('Enter the question:'), sg.InputText(key='question', size=105, tooltip="Enter the question.")],
        [sg.Text('Enter the correct answer:'), sg.InputText(key='correct_answer', size=75, tooltip="Enter the answer.")],
        [sg.Text('Enter the wrong answers:'), sg.InputText(key='wrong_answers', size=100, tooltip="Enter some related but incorrect answers, separated by commas.")],
        [sg.Text('Enter the time given to answer:'), sg.InputText(key='time_given', size=3, tooltip="Enter an integer number of seconds. Average is 10-20, default (if you leave it blank) is 15")],
        [sg.Button('Add'), sg.Button('Cancel')]
    ]

    questionEditorWindow = sg.Window('Question Editor', questionEditorLayout, finalize=True, keep_on_top=True)
    return questionEditorWindow

def save_quiz(file_path):
    with open(f'{file_path}', 'w') as file:
        savedData = {
            "title": mainWindow['quiz_name'].get(),
            "difficulty": int(values['difficulty']),
            "randomOrder": mainWindow['randomOrder'].get(),
            "listOfQuestions": questionList
        }
        json.dump(savedData, file, default=vars)

def Add():
    questionEditorWindow = make_questionEditorWindow()
    editorEvent, editorValues = questionEditorWindow.read()
    if editorEvent == 'Add':
        question = editorValues['question']
        correct_answer = editorValues['correct_answer']
        wrong_answers = editorValues['wrong_answers'].split(',')
        try:
            time_given = int(editorValues['time_given'])
        except ValueError:
            time_given = 15
        newquestion = QuizQuestion(question, correct_answer, wrong_answers, time_given)
        is_silly_question, reason = is_silly(question, correct_answer, wrong_answers, time_given, questionList)
        if is_silly_question:
            sg.Popup(f"Silly question detected: {reason}", keep_on_top=True, auto_close=True, auto_close_duration=1.5)
            questionEditorWindow.close()
        else:
            questionList.append(newquestion)
            questionEditorWindow.close()
            mainWindow["quizquestionentry"].update(questionList)
    if editorEvent == 'Cancel':
        questionEditorWindow.close()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        prog='QuizCreator',
        description='Side program for QuizMaster, to make quizzes.',
        )
    parser.add_argument('-q', '--quizPath', nargs='?', const="")
    args = parser.parse_args()

    if args.quizPath is not None:
        print("Loading quiz: ", args.quizPath)
        try:
            filename = args.quizPath
            event = 'Open'
        except Exception as ex:
            print("Error:", ex)
            sys.exit()
        try:
            with open(filename, 'r') as file:
                try:
                    quizDicts = json.load(file)
                    questionList = []
                    for q in quizDicts["listOfQuestions"]:
                        qq = QuizQuestion(**q)
                        is_silly_question, reason = is_silly(qq.question, qq.correctAnswer, qq.wrongAnswers, qq.timeout, questionList)
                        if is_silly_question:
                            sg.Popup(f"Silly question detected: {reason}", keep_on_top=True, auto_close=True, auto_close_duration=1.5)
                            break
                        questionList.append(qq)
                    mainWindow["quizquestionentry"].update(questionList)
                    titleofquiz = quizDicts["title"]
                    mainWindow["quiz_name"].update(titleofquiz)
                    current_file_path = filename
                except Exception as ex:
                    sg.Popup(f"Error with this file! {ex}", keep_on_top=True, auto_close=True, auto_close_duration=1.5)
                    print(f"Error with this file! {ex}")
        except FileNotFoundError:
            print(f"{filename} does not exist!")

    while True:
        event, values = mainWindow.read()

        if event == 'quizquestionentry':
            changes = True
            if len(values['quizquestionentry']) > 0:
                answers = ("correct answer:", values['quizquestionentry'][0].correctAnswer, "wrong answers:", values['quizquestionentry'][0].wrongAnswers)
                outputtext = "Correct answer: \n" + answers[1] + "\n Wrong answers:\n" + str(answers[3])
                mainWindow["textbox"].update(outputtext)

        if event == sg.WIN_CLOSED or event == 'Quit':
            if changes:
                if sg.popup_yes_no("You have unsaved changes! Save before you leave?", keep_on_top=True) == "No":
                    break
                else:
                    changes = False
                    save_quiz(current_file_path)
                    break
            break

        if values['difficulty'] not in difficultyList:
            mainWindow["difficulty"].update(3)

        if event == 'Restart':          
            try:
                subprocess.Popen(["/usr/bin/python", "quizcreator",])
            except:
                subprocess.Popen(["/usr/bin/python3", "quizcreator"])
            quit()      

        if event == 'Clear':
            if changes:
                if sg.popup_yes_no("You have unsaved changes! Save before you clear?", keep_on_top=True) == "No":
                    pass
                else:
                    changes = False
                    save_quiz(current_file_path)
                    pass
            pass
            questionList = []
            mainWindow["quizquestionentry"].update(questionList)
            mainWindow["quiz_name"].update("")
            current_file_path = None

        if event == 'New':
            try:
                subprocess.Popen(["/usr/bin/python", "quizcreator",])
            except:
                subprocess.Popen(["/usr/bin/python3", "quizcreator"])

        if event == 'Edit Question':
            try:
                index = int(''.join(map(str, mainWindow["quizquestionentry"].get_indexes())))
                quizQuestion = questionList[index]
            except ValueError:
                try:
                    quizQuestion = questionList[-1]
                except IndexError:
                    Add()
                    continue

            questionEditorWindow = make_questionEditorWindow()
            questionEditorWindow['question'].update(quizQuestion.question)
            questionEditorWindow['correct_answer'].update(quizQuestion.correctAnswer)
            questionEditorWindow['wrong_answers'].update(','.join(str(e) for e in quizQuestion.wrongAnswers))
            questionEditorWindow['time_given'].update(quizQuestion.timeout)
            editorEvent, editorValues = questionEditorWindow.read()
            if editorEvent == 'Add':
                question = editorValues['question']
                correct_answer = editorValues['correct_answer']
                wrong_answers = editorValues['wrong_answers'].split(',')
                try:
                    time_given = int(editorValues['time_given'])
                except ValueError:
                    time_given = 15
                newquestion = QuizQuestion(question, correct_answer, wrong_answers, time_given)
                newquestion = QuizQuestion(question, correct_answer, wrong_answers, 15)
                is_silly_question, reason = is_silly(question, correct_answer, wrong_answers, time_given, questionList)
                if is_silly_question:
                    sg.Popup(f"Silly question detected: {reason}", keep_on_top=True, auto_close=True, auto_close_duration=1.5)
                    questionEditorWindow.close()
                else:
                    questionList[index] = newquestion
                    questionEditorWindow.close()
                    mainWindow["quizquestionentry"].update(questionList)
            if editorEvent == 'Cancel':
                questionEditorWindow.close()

        if event == 'Add Question' or event == 'a':
            Add()
           
        if event == 'Duplicate Question' or event == 'd':
            try:
                index = int(''.join(map(str, mainWindow["quizquestionentry"].get_indexes())))
                quizQuestion = questionList[index]
                new_question = QuizQuestion(quizQuestion.question, quizQuestion.correctAnswer, quizQuestion.wrongAnswers, quizQuestion.timeout)
                questionList.append(new_question)
                mainWindow["quizquestionentry"].update(questionList)
            except ValueError:
                sg.Popup("Select a question to duplicate!", keep_on_top=True, auto_close=True, auto_close_duration=1.5)

        if event == 'Save As' or event == 's':
            changes = False
            current_file_path = sg.popup_get_file('', save_as=True, keep_on_top=True, no_window=True, initial_folder="Quizzes",
                                                file_types=(("All JSON Files", "*.json"), ("All Files", "*.*")))
            if current_file_path:
                save_quiz(current_file_path)

        if event == 'Save':
            changes = False
            try:
                save_quiz(current_file_path)
            except:
                pass

        if event == 'Open' or event == 'o':
            if changes:
                if sg.popup_yes_no("You have unsaved changes! Save before you leave?", keep_on_top=True) == "No":
                    pass
                else:
                    changes = False
                    save_quiz(current_file_path)
                    pass
            pass

            try:
                filename = sg.popup_get_file("Open quiz", initial_folder="Quizzes", no_window=True)
                if filename:
                    with open(filename, 'r') as file:
                        try:
                            quizDicts = json.load(file)
                            questionList = []
                            for q in quizDicts["listOfQuestions"]:
                                qq = QuizQuestion(**q)
                                is_silly_question, reason = is_silly(qq.question, qq.correctAnswer, qq.wrongAnswers, qq.timeout, questionList)
                                if is_silly_question:
                                    sg.Popup(f"Silly question detected: {reason}", keep_on_top=True, auto_close=True, auto_close_duration=1.5)
                                    pass
                                questionList.append(qq)
                            mainWindow["quizquestionentry"].update(questionList)
                            titleofquiz = quizDicts["title"]
                            mainWindow["quiz_name"].update(titleofquiz)
                            try:
                                difficulty = quizDicts["difficulty"]
                                randomOrder = quizDicts["randomOrder"]
                                mainWindow["randomOrder"].update(randomOrder)
                                mainWindow["difficulty"].update(difficulty)
                            except:
                                pass                    
                            current_file_path = filename
                        except Exception as e:
                            sg.Popup(f"Error with this file! {e}", keep_on_top=True, auto_close=True, auto_close_duration=1.5)
            except TypeError:
                pass

        if event == 'Delete Question' or event == 'Delete':
            try:
                index = int(''.join(map(str, mainWindow["quizquestionentry"].get_indexes())))
                questionList.pop(index)
            except ValueError:
                sg.Popup("Select a message to delete!")

            mainWindow["quizquestionentry"].update(questionList)

        if event == 'Play':
            if questionList is not None:
                save_quiz(current_file_path)
                changes = False
                try:
                    subprocess.Popen(["/usr/bin/python", "quiz.py", f"-q{current_file_path}", "-gpractice", "-v0.0"])
                except:
                    subprocess.Popen(["/usr/bin/python3", "quiz.py", f"-q{current_file_path}", "-gpractice", "-v0.0"])
            else:
                sg.Popup("Please make a quiz first!", keep_on_top=True, auto_close=True, auto_close_duration=1.5)

        if event == 'Tutorials':
            webbrowser.open("https://quizmaster-world.github.io/Tutorials/QuizMaster.html")

        if event == 'QuizMaster Repository':
            webbrowser.open("https://github.com/hermonochy/QuizMaster/")
        if event == 'QuizMaster Organisation':
            webbrowser.open("https://github.com/QuizMaster-world/")

