@echo off
call venv\Scripts\activate || call setup.bat
echo Activated virtual environment...
echo Fetching Quizzes...
cd Quizzes && git pull && cd .. || echo Unable to update...
echo Running QuizMaster...
python quiz.py || (call setup.bat && python quiz.py)